### ISSUE TITLE
Keep package.json up to date with dependencies

### ISSUE THREAD

**Issue by chinedufn** [acucciniello/SilentSight#2]
Most of the dependencies that you're using aren't in your `package.json`.

I should be able to clone this repo, `npm install` then get all of the proper dependencies.

A good way to make sure you're always adding your dependencies is to use the `--save` flag when you install a new package. This automatically adds it to your `package.json`

For example.. To install `got` and save the dependency to your `package.json`

`npm install --save got`

**Comment by chinedufn** [comment]
Note: You don't need to save `http`. That's a node core module

**Comment by chinedufn** [comment]
Looks like you fixed this? Comment and close issues when you take care of them!

**Comment by acucciniello** [comment]
It is only fixed in my database branch not in my master branch
